// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartInventory.Repository;

#nullable disable

namespace SmartInventory.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609140700_AddMissingSequences")]
    partial class AddMissingSequences
    {
    }
}
